//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihale_Uygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class ihale_tablosu
    {
        public int id { get; set; }
        public int musteri_id { get; set; }
        public int urun_kategorisi { get; set; }
        public string urun_fotografi { get; set; }
        public string urun_adi { get; set; }
        public string aciklama { get; set; }
        public int stok_adet { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
    
        public virtual kategori_tablosu kategori_tablosu { get; set; }
        public virtual musteri_tablosu musteri_tablosu { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
