//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihale_Uygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ihale_tablosu_view
    {
        public int ihale_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public string musteri_adi { get; set; }
        public string musteri_soyadi { get; set; }
        public string firma_adi { get; set; }
        public string urun_fotografi { get; set; }
        public int urun_kategorisi { get; set; }
        public string urun_adi { get; set; }
        public string aciklama { get; set; }
        public int stok_adet { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
        public long aktif { get; set; }
    }
}
