//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihale_Uygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori_tablosu
    {
        public kategori_tablosu()
        {
            this.ihale_tablosu = new HashSet<ihale_tablosu>();
        }
    
        public int kategori_id { get; set; }
        public string kategori_ad { get; set; }
    
        public virtual ICollection<ihale_tablosu> ihale_tablosu { get; set; }
    }
}
