//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihale_Uygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesaj_tablosu
    {
        public int mesaj_id { get; set; }
        public int gonderen_id { get; set; }
        public int alici_id { get; set; }
        public int ihale_id { get; set; }
        public string mesaj { get; set; }
        public Nullable<int> mesaj_cevap_id { get; set; }
        public Nullable<int> yanit { get; set; }
    }
}
