//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ihale_Uygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class musteri_tablosu
    {
        public musteri_tablosu()
        {
            this.ihale_tablosu = new HashSet<ihale_tablosu>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Lütfen adınızı giriniz.")]
        public string musteri_adi { get; set; }
        [Required(ErrorMessage = "Lütfen soyadınızı giriniz.")]
        public string musteri_soyadi { get; set; }
        public Nullable<int> tc { get; set; }
        public Nullable<int> vergi_no { get; set; }
        public string firma_adi { get; set; }
        [Required(ErrorMessage = "Lütfen adresinizi giriniz.")]
        public string adres { get; set; }
        public string telefon { get; set; }
        [Required(ErrorMessage = "Lütfen e-postanızı giriniz.")]
        public string e_posta { get; set; }
        [Required(ErrorMessage = "Lütfen kullanıcı adınızı giriniz.")]
        public string kullanici_adi { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Lütfen şifrenizi giriniz.")]
        public string sifre { get; set; }
        public float puan { get; set; }
        public int count { get; set; }
        public float toplam { get; set; }

        public string GirisYapError { get; set; }
        public string KayitOlError { get; set; }

        public virtual ICollection<ihale_tablosu> ihale_tablosu { get; set; }
    }
}
